=== xiaoyunchengzhu/XmlConvertObject/app/src/main/assets/schema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.w3school.com.cn"
    xmlns="http://www.w3school.com.cn"
    elementFormDefault="qualified"
    >



    <xs:element name="config"  >
        <xs:complexType>

            <xs:choice  minOccurs="0" maxOccurs="unbounded">
                <xs:element  name="boolean" type="boolean"></xs:element>
                <xs:element    name="int" type="int"></xs:element>
                <xs:element name="char" type="char"></xs:element>
                <xs:element  name="double" type="double"></xs:element>
                <xs:element  name="float" type="float"></xs:element>
                <xs:element  name="long" type="long"></xs:element>
                <xs:element  name="short" type="short"></xs:element>
                <xs:element  name="byte" type="byte"></xs:element>
                <xs:element  name="string" type="string"></xs:element>
                <xs:element  name="object" type="object"></xs:element>
                <xs:element  name="list" type="list"></xs:element>
                <xs:element  name="map" type="map"></xs:element>
                <xs:element  name="null"></xs:element>
            </xs:choice>
        </xs:complexType>
    </xs:element>

    <xs:group name="config">
        <xs:choice id="config">
            <xs:element id="boolean" name="boolean" type="boolean"></xs:element>
            <xs:element  id="int"  name="int" type="int"></xs:element>
            <xs:element id="char" name="char" type="char"></xs:element>
            <xs:element id="double" name="double" type="double"></xs:element>
            <xs:element id="float" name="float" type="float"></xs:element>
            <xs:element id="long" name="long" type="long"></xs:element>
            <xs:element id="short" name="short" type="short"></xs:element>
            <xs:element id="byte" name="byte" type="byte"></xs:element>
            <xs:element  name="string" type="string"></xs:element>
            <xs:element id="object" name="object" type="object"></xs:element>
            <xs:element id="list" name="list" type="list"></xs:element>
            <xs:element id="map" name="map" type="map"></xs:element>
            <xs:element id="null" name="null"></xs:element>
        </xs:choice>
    </xs:group>




    <xs:complexType name="boolean"  >
        <xs:simpleContent>
            <xs:extension base="xs:boolean">
            <xs:attribute name="id" type="xs:token"   />
            <xs:attribute name="ref" type="xs:string"  default="@boolean" />
            </xs:extension>
        </xs:simpleContent>

    </xs:complexType>
    <xs:complexType name="int">
        <xs:simpleContent>
            <xs:extension base="xs:int">
            <xs:attribute name="id" type="xs:token"  />
            <xs:attribute name="ref" type="xs:string"  default="@int" />
            </xs:extension>
        </xs:simpleContent>

    </xs:complexType>
    <xs:complexType name="char">
        <xs:simpleContent>
            <xs:extension base="xs:char">
            <xs:attribute name="id" type="xs:string"  />
            <xs:attribute name="ref" type="xs:string"  default="@char" />
            </xs:extension>
        </xs:simpleContent>

    </xs:complexType>
    <xs:complexType name="double">
        <xs:simpleContent>
        <xs:extension base="xs:double">
        <xs:attribute name="id" type="xs:token"  />
        <xs:attribute name="ref" type="xs:string"  default="@double" />
        </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="float">
        <xs:simpleContent>
            <xs:extension base="xs:float">
            <xs:attribute name="id" type="xs:token"  />
            <xs:attribute name="ref" type="xs:string"  default="@float" />
            </xs:extension>
        </xs:simpleContent>

    </xs:complexType>
    <xs:complexType name="long">
        <xs:simpleContent >
            <xs:extension base="xs:long">
        <xs:attribute name="id" type="xs:token"  />
        <xs:attribute name="ref" type="xs:string"  default="@long" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="short">
        <xs:simpleContent>
            <xs:extension base="xs:short">
            <xs:attribute name="id" type="xs:token" />
            <xs:attribute name="ref" type="xs:string"  default="@short" />
            </xs:extension>
        </xs:simpleContent>

    </xs:complexType>
    <xs:complexType name="byte">
        <xs:simpleContent>
            <xs:extension base="xs:byte">
                <xs:attribute name="id" type="xs:token" />
                <xs:attribute name="ref" type="xs:string"  default="@byte" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="string" mixed="true">
        <xs:complexContent>
            <xs:extension base="xs:string">
                <xs:sequence>
                    <xs:element name="null"/>
                </xs:sequence>
                <xs:attribute name="id" type="xs:token" />
                <xs:attribute name="ref" type="xs:string" default="@string/"  form="qualified"  />
            </xs:extension>
        </xs:complexContent>

    </xs:complexType>


    <xs:complexType name="object" mixed="true" >
        <xs:annotation>
            <xs:documentation>
                对象的配置
            </xs:documentation>
        </xs:annotation>
        <xs:choice minOccurs="0" maxOccurs="unbounded" >
            <xs:element name="property" type="property" />

        </xs:choice>
        <xs:attribute name="id" type="xs:token"></xs:attribute>
        <xs:attribute name="ref" type="xs:string" default="@object"></xs:attribute>
        <xs:attribute name="class" type="xs:string"></xs:attribute>
        <xs:attribute name="p" type="string" form="qualified"/>

        <xs:anyAttribute  />


    </xs:complexType>
     <xs:complexType name="property" mixed="true">
         <xs:choice minOccurs="0" maxOccurs="unbounded">
             <xs:group ref="config"></xs:group>

         </xs:choice>
         <xs:attribute  name="name" type="xs:string" use="required"></xs:attribute>
         <xs:attribute name="value" type="xs:string" default="@" ></xs:attribute>
         <xs:anyAttribute/>
     </xs:complexType>
    <xs:complexType name="list" mixed="true">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:group ref="config"></xs:group>

        </xs:choice>
        <xs:attribute name="id" type="xs:string"></xs:attribute>
        <xs:attribute name="ref" type="xs:string" default="@object"></xs:attribute>
        <xs:anyAttribute/>
    </xs:complexType>
    <xs:complexType name="map" mixed="true">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <!--<xs:group ref="config"></xs:group>-->
            <xs:element name="entity" type="entity"></xs:element>
            <xs:element name="null"/>
        </xs:choice>
        <xs:attribute name="id" type="xs:token"></xs:attribute>
        <xs:attribute name="ref" type="xs:string" default="@object"></xs:attribute>

    </xs:complexType>


    <xs:complexType name="entity" mixed="true"   >
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="value" type="entity_item" ></xs:element>
            <xs:element name="key" type="entity_item"></xs:element>
        </xs:choice>
        <xs:attribute name="value"  default="@"  ></xs:attribute>
        <xs:attribute name="key"     default="@"></xs:attribute>
    </xs:complexType>
     <xs:simpleType name="restration">
         <xs:restriction >
             <xs:pattern value="(@string)+"></xs:pattern>
         </xs:restriction>
     </xs:simpleType>
    <xs:complexType name="entity_item" mixed="true">
        <xs:choice minOccurs="0" maxOccurs="1">
            <xs:group ref="config"></xs:group>
        </xs:choice>
    </xs:complexType>








</xs:schema>

=== xiaoyunchengzhu/XmlConvertObject/app/src/main/assets/configResource.xml
<?xml version="1.0" encoding="utf-8"?>
<config xmlns="http://www.w3school.com.cn" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:noNamespaceSchemaLocation="schema.xsd"


>
    <!--xmlns:p="http://www.w3.org/1999/xhtml"-->
    <!-- 一： id：唯一标识符，获取对象用。
              class:对象的包名，路径。
              ref:指向另一个项作为此项。
              propertyName ：属性为对象的属性名字。
              @Type/id ：指定 Id，类型的节点对象。
              其余 string和八个基本类型的元素。
         二：
              java基本类型 特殊类；
              s例如：tring :String 节点。集合直接作为属性或者成员的时候不写d.和对象一样。
              string 的值直接声明在内容里。如<string>我的世界 </string>
         三 ：
              引用。
                    对象属性的引用：如果一个对象的属性是另一个节点对象，则用@Type/id 这种方式指定另一个 xml的对象作为此对象的属性值。
                    集合成员的引用：集合成员都是来表示集合中增加一个对象想增加已经定义节点的属性，比如   <object ref="@object/response1"  ></object>
                    这种方式，表示引用id为response1,类型为object的对象。
              对象属性本节点初始化：如果一个对象的属性是一个对象并且自定义到这个对象的节点中，则在这个对象节点内容也生成子节点表示属性，并且指定propertyName，
              比如  <object class="com.xiaoyunchengzhu.xmlconvertobject.model.Response"
            id="response2">
            <property name="error" value="http://www.baidutest.com"/>
            <property name="success">300</property>
            <property name="type">get</property>
            <property name="dataUrlBean" >
                <object class="com.xiaoyunchengzhu.xmlconvertobject.model.DataUrlBean">
                    <property name="url" value="http://www.baidutest.com"/>
                    <property name="name" value="login.name"/>
                    <property name="expires" value="200"/>
                    <property name="type" >get</property>
                </object>
            </property>

        </object>
                 也可以对象属性引用：
                  <object class="com.xiaoyunchengzhu.xmlconvertobject.model.Response"
            id="response1"

            >
            <property name="error" value="http"/>
            <property name="success">300</property>
            <property name="type">get</property>
            <property name="dataUrlBean" value="@object/dataUrlBean1"/>
        </object>

     -->
        <list id="list1"  >
            <object class="com.xiaoyunchengzhu.xmlconvertobject.model.DataUrlBean">
                <property name="url" value="http://www.baidutest.com"/>
                <property name="name" value="test"/>
                <property name="expires" value="300"/>
                <property name="type" value="get"/>
            </object>

            <object class="com.xiaoyunchengzhu.xmlconvertobject.model.DataUrlBean"
                >
            <property name="url" value="http://www.baidutest.com"/>
            <property name="name" value="login.name"/>
            <property name="expires" value="200"/>
            <property name="type" >get</property>
            </object>

        </list>
        <list id="list2">
            <string>you are gay</string>
            <string>you are kio</string>
            <string>you are w</string>
            <string>you are bak</string>
            <string>you are fuck</string>


        </list>
        <list  id="list3"  >
            <object class="com.xiaoyunchengzhu.xmlconvertobject.model.Response">
                <property name="error" value="http://www.baidutest.com"/>
                <property name="success">300</property>
                <property name="type">get</property>
                <property name="dataUrlBean" value="@object/dataUrlBean1"/>
                </object>

            <object class="com.xiaoyunchengzhu.xmlconvertobject.model.Response">
                <property name="error" value="http://www.baidutest.com"/>
                <property name="success">300</property>
                <property name="type">get</property>
                <property name="dataUrlBean" >
                    <object class="com.xiaoyunchengzhu.xmlconvertobject.model.DataUrlBean">
                        <property name="url" value="http://www.baidutest.com"/>
                        <property name="name" value="login.name"/>
                        <property name="expires" value="200"/>
                        <property name="type" >get</property>
                    </object>
                </property>
                </object>
            <object ref="@object/response1"  ></object>

            <object class="com.xiaoyunchengzhu.xmlconvertobject.model.Response" >
                <property name="error" value="@string/boy1"></property>
                <property name="success" value="100"></property>
                <property name="type" value="get"/>
                <property name="dataUrlBean" value="@@object/response1"/>
            </object>

        </list>


    <map id="map1">
        <entity value="wfew" key="wef"/>
         <entity>
             <key>key1</key><value>jiol</value>
         </entity>
        <entity>
           <key>
               <string>
                   我的世界我做主
               </string>
           </key>
            <value>
             grefe
            </value>
        </entity>
        <entity  key="@string/boy1" value="@object/response1"></entity>
    </map>
        <object class="com.xiaoyunchengzhu.xmlconvertobject.model.DataUrlBean"
            id="dataUrlBean1">
            <property name="url" value="http://www.baidutest.com"/>
            <property name="name" value="login.name"/>
            <property name="expires" value="200"/>
            <property name="type" >get</property>
        </object>
        <object class="com.xiaoyunchengzhu.xmlconvertobject.model.Person"
            id="person1">
            <property name="name" value="sofe"/>
            <property name="age">52</property>
            <property name="list" value="@list/list1"/>
        </object>
    <object class="com.xiaoyunchengzhu.xmlconvertobject.model.Person">
        <property name="name" value="wfin"/>
        <property name="age" value="12"></property>
        <property name="list" value="@list/list1"/>
    </object>
        <object class="com.xiaoyunchengzhu.xmlconvertobject.model.Response"
            id="response1"

            >
            <property name="error" value="http"/>
            <property name="success">300</property>
            <property name="type">get</property>
            <property name="dataUrlBean" value="@object/dataUrlBean1"/>
        </object>


        <object class="com.xiaoyunchengzhu.xmlconvertobject.model.Response"
            id="response2">
            <property name="error" value="http://www.baidutest.com"/>
            <property name="success">300</property>
            <property name="type">get</property>
            <property name="dataUrlBean" >
                <object class="com.xiaoyunchengzhu.xmlconvertobject.model.DataUrlBean">
                    <property name="url" value="http://www.baidutest.com"/>
                    <property name="name" value="login.name"/>
                    <property name="expires" value="200"/>
                    <property name="type" >get</property>
                </object>
            </property>

        </object>





    <char id="char1" >f</char>
    <string id="lihua">李华</string>
    <string id="error">swfeg</string>
    <int id="int1">52</int>
    <int id="wf">1</int>
    <long id="long1">12345678</long>
    <float id="float1">12.0</float>
    <char id="char1">a</char>
    <double id="double1">213.55</double>
    <boolean ref="@boolean/boolean2" id="boolean1">true</boolean>
    <boolean  id="boolean2" >false</boolean>
    <string id="boy1">I am a 小男孩</string>


</config>
